### IND320 project work part 1 
Name: Mina Johanne Askerød <br>
Date: <br>
Git <br>
Streamlit

#### Import packages

In [ ]:
# data handling 
import pandas as pd

# visualizations 
import plotly.express as px

#### Reading the data

In [11]:
dat = pd.read_csv('../data/reservoirs.csv') # reading in the data 
dat.head()

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,0001-01-01T00:00:00,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25T13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,0001-01-01T00:00:00,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,0001-01-01T00:00:00,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,0001-01-01T00:00:00,0.311122,-0.010301

In [3]:
dat.shape # dimensions

(14877, 11)

In [12]:
dat.describe()

,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,fyllingsgrad_forrige_uke,endring_fyllingsgrad
count,14877.000000,14877.000000,14877.000000,14877.000000,14877.000000,14877.000000,14877.000000,14877.000000
mean,2.333333,2010.346038,26.405929,0.618852,29.145860,18.139713,0.618890,-0.000038
std,1.490762,9.146696,15.017910,0.214850,22.739070,15.966211,0.214843,0.031385
min,0.000000,1995.000000,1.000000,0.055160,6.003264,0.331142,0.055160,-0.242484
25%,1.000000,2002.000000,13.000000,0.456234,17.390587,7.321973,0.456356,-0.022395
50%,2.000000,2010.000000,26.000000,0.648049,23.237715,14.501389,0.648114,-0.007072
75%,3.000000,2018.000000,39.000000,0.802135,34.043590,22.203530,0.802133,0.016277
max,5.000000,2026.000000,53.000000,1.020072,87.437580,84.544820,1.020037,0.336623

In [5]:
dat.dtypes

dato_Id                         str
omrType                         str
omrnr                         int64
iso_aar                       int64
iso_uke                       int64
fyllingsgrad                float64
kapasitet_TWh               float64
fylling_TWh                 float64
neste_Publiseringsdato          str
fyllingsgrad_forrige_uke    float64
endring_fyllingsgrad        float64
dtype: object

Renaming the column names to english and understandable names.

In [14]:
map_names = {
    "dato_Id": "date",
    "omrType": "area_type",
    "omrnr": "area_number",
    "iso_aar": "iso_year",
    "iso_uke": "iso_week",
    "fyllingsgrad": "filling_level",
    "kapasitet_TWh": "capacity_TWh",
    "fylling_TWh": "stored_energy_TWh",
    "neste_Publiseringsdato": "next_publication_date",
    "fyllingsgrad_forrige_uke": "filling_level_previous_week",
    "endring_fyllingsgrad": "change_in_filling_level"
} # map names dictionary 
dat = dat.rename(columns=map_names) # map names

Converting column "date" to a datetime object and sorting the dates.

In [15]:
dat["date"].dtype

In [17]:
dat["date"] = pd.to_datetime(dat["date"])
dat["date"].dtype

dtype('<M8[us]')

In [20]:
dat = dat.sort_values("date")
dat.head()

,date,area_type,area_number,iso_year,iso_week,filling_level,capacity_TWh,stored_energy_TWh,next_publication_date,filling_level_previous_week,change_in_filling_level
3468,1995-01-08,EL,5,1995,1,0.616448,17.390587,10.720388,0001-01-01T00:00:00,0.614288,0.002160
3361,1995-01-08,EL,4,1995,1,0.558864,21.079208,11.780413,0001-01-01T00:00:00,0.801348,-0.242484
5036,1995-01-08,EL,3,1995,1,0.602376,8.920932,5.373754,0001-01-01T00:00:00,0.596027,0.006349
3113,1995-01-08,EL,1,1995,1,0.621467,6.003264,3.730831,0001-01-01T00:00:00,0.734888,-0.113421
7739,1995-01-08,EL,2,1995,1,0.630947,34.043590,21.479713,0001-01-01T00:00:00,0.777604,-0.146657

In [ ]:
dat["area_number"].value_counts() # distribution over areas

area_number
3    3306
1    3306
2    3306
5    1653
4    1653
0    1653
Name: count, dtype: int64

In [36]:
areas_per_date = dat.groupby("date")["area_number"].nunique()

areas_per_date.value_counts()

area_number
6    1653
Name: count, dtype: int64

In [37]:
dat["area_type"].value_counts()

area_type
EL      8265
VASS    4959
NO      1653
Name: count, dtype: int64

In [ ]:
dat[["area_type", "area_number"]].drop_duplicates().sort_values(
    ["area_type", "area_number"]
)

#### Plot of each column

##### Measurements over time

In [35]:
line_cols = [
    "filling_level",
    "capacity_TWh",
    "stored_energy_TWh",
    "filling_level_previous_week",
    "change_in_filling_level"
]

for col in line_cols: 
    fig = px.line(
        dat, 
        x="date",
        y=col, 
        #color="area_number",
        title=f"{col} over time"
    )
    fig.update_layout(template="plotly_white")
    fig.show()

kommentere...?

##### Distributions of categorical and discrete variables

In [27]:
hist_cols = [
    "area_number",
    "iso_year",
    "iso_week"
]

for col in hist_cols: 
    fig = px.histogram(
        dat, 
        x=col,
        title=f"Distribution of {col}"
    )
    fig.update_layout(template="plotly_white")
    fig.show()

Kommentere..?

#### Plot of all columns together

the variables are on different scales - scaling the variables before plotting

In [41]:
measure_cols = [
    "filling_level",
    "capacity_TWh",
    "stored_energy_TWh",
    "filling_level_previous_week",
    "change_in_filling_level"
]

plot_data = dat.groupby("date")[measure_cols].mean().reset_index()

In [42]:
# Min-max scale each numerical column
for col in measure_cols:
    plot_data[col] = (
        (plot_data[col] - plot_data[col].min())
        / (plot_data[col].max() - plot_data[col].min())
    )

In [44]:
fig = px.line(
    plot_data,
    x="date",
    y=measure_cols,
    title="Scaled reservoir measurements over time"
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Date",
    yaxis_title="Scaled value",
    legend_title="Variable"
)

fig.show()

#### log (description of compulsory work)

#### Use of AI

- oversette navn 
- bruke plotly 
- skalere + hvilke kolonner å plotte i samlet plot